if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"


set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set -g mouse on
set -g set-clipboard on
set-option -g default-shell /bin/zsh
set -g pane-base-index 1
set -g pane-border-status top
set -g pane-border-format "#{pane_index} #{?@custom_title,#{@custom_title},#{pane_title}}"
setw -g automatic-rename off

bind-key T command-prompt -p "Pane title:" "set-option -p @custom_title '%%'"
bind-key M-t set-option -p -u @custom_title  # prefix + Alt-t to clear custom title

# Set prefix to Ctrl+s
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# Use vim keys in copy mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

# Use xterm keys
set -g xterm-keys on
set -g extended-keys on

# Split window with prefix + arrow keys
bind Up split-window -b -v      # split above
bind Down split-window -v       # split below
bind Left split-window -b -h    # split left
bind Right split-window -h      # split righ

run-shell 'for i in $(seq 0 9); do tmux bind-key -n M-$i select-pane -t $i; done'

# Unbind Meta
unbind -n M-h
unbind -n M-l
unbind -n M-k
unbind -n M-j
unbind -n M-H
unbind -n M-L
unbind -n M-K
unbind -n M-J

# pane switch
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# pane adjust (Option + Shift)
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5
bind -r K resize-pane -U 5
bind -r J resize-pane -D 5

set -g @tpm_plugins '          \
  tmux-plugins/tpm             \
  catppuccin/tmux              \
  tmux-plugins/tmux-resurrect  \
  tmux-plugins/tmux-continuum  \
'

# Monokai Pro 样式配置
set -g @resurrect-dir '~/.tmux/resurrect'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'  # 每 15 分钟自动保存一次

# 3. 增强：保存终端内容和 Neovim 状态（可选）
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'


# Catppuccin theme
set -g @catppuccin_flavour 'mocha'
run '~/.tmux/plugins/tmux/catppuccin.tmux'

# Bottom
run '~/.tmux/plugins/tpm/tpm'
