if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"


set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set -g mouse on
set-option -g default-shell /bin/zsh
set -g pane-base-index 1
set -g pane-border-status top
set -g pane-border-format "#{pane_index} #{pane_title}"
setw -g automatic-rename off

bind-key T command-prompt -p "Pane title:" "select-pane -T '%%'"

# Set prefix to Ctrl+s
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# Use xterm keys
set -g xterm-keys on
set -g extended-keys on

# Split window with prefix + arrow keys
bind Up split-window -b -v      # split above
bind Down split-window -v       # split below
bind Left split-window -b -h    # split left
bind Right split-window -h      # split righ

run-shell 'for i in $(seq 0 9); do tmux bind-key -n M-$i select-pane -t $i; done'

# Unbind Meta
unbind -n M-h
unbind -n M-l
unbind -n M-k
unbind -n M-j
unbind -n M-H
unbind -n M-L
unbind -n M-K
unbind -n M-J

# pane switch
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# pane adjust (Option + Shift)
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5
bind -r K resize-pane -U 5
bind -r J resize-pane -D 5

set -g @tpm_plugins '          \
  tmux-plugins/tpm             \
  catppuccin/tmux              \
'

# Catppuccin 样式配置
set -g @catppuccin_flavour 'macchiato'
set -g @catppuccin_window_tabs_enabled on


# Bottom
run '~/.tmux/plugins/tpm/tpm'
